#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME "SM-G530FZ"
#define BTA_DISABLE_DELAY 1000 /* in milliseconds */
#define BLUETOOTH_QTI_SW TRUE
#define BLE_VND_INCLUDED TRUE

#endif
